### ISSUE TITLE
`@inject()` explained

### ISSUE THREAD

**Issue by uditalias** [flowck/user_injex_depedency_injection_typescript#1]
Hey @flowck,

I just saw you're new project, so exciting! 🤩

Want to make sure you're all set - the `@inject()` decorator can auto-detect the type of the injectable module by its name.

So instead of:

```typescript
@inject(UserService) private userService!: UserService;
```
You can use:
```typescript
@inject() private userService!: UserService;
```

You can pass into the `@inject()` decorator a type or a name when you manually define the name of your module or the property name is not the same as the module name like so:

```typescript
@define("myService")
@singleton()
class UserService {
    ...
}
```

In such cases, Injex don't know about `userService` so you have 2 options:

```typescript
@inject() private myService!: UserService;
// or
@inject("myService") private userService!: UserService;
```

Or using the type:

```typescript
@inject(UserService) private userService!: UserService;
```

Hope it's clear, LMK if not :)

**Comment by flowck** [comment]
Hi @uditalias, 

Thanks for the tip. I'll refactor this repo, and the other project I am working on as well. So far my experience has been great, no issues whatsoever, and thanks to Injex I was able to implement a better architecture for a bigger project. I love it.
